<?php

return [
    'countries' => [
        'Australia',
        'Austria',
        'Belgium',
        'Brazil',
        'Canada',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Germany',
        'India',
        'Ireland',
        'Italy',
        'Japan',
        'Latvia',
        'Lithuania',
        'Netherlands',
        'New Zealand',
        'Norway',
        'Poland',
        'Portugal',
        'Singapore',
        'South Africa',
        'Spain',
        'Sweden',
        'Switzerland',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
    ],

    'city_map' => [
        'Australia' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'],
        'Austria' => ['Vienna', 'Salzburg', 'Graz', 'Linz'],
        'Belgium' => ['Brussels', 'Antwerp', 'Ghent', 'Bruges'],
        'Brazil' => ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'],
        'Canada' => ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa'],
        'Denmark' => ['Copenhagen', 'Aarhus', 'Odense'],
        'Estonia' => ['Tallinn', 'Tartu', 'Narva'],
        'Finland' => ['Helsinki', 'Espoo', 'Tampere'],
        'France' => ['Paris', 'Lyon', 'Marseille', 'Nice', 'Toulouse'],
        'Germany' => ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne'],
        'India' => ['Delhi', 'Mumbai', 'Bengaluru', 'Hyderabad', 'Chennai'],
        'Ireland' => ['Dublin', 'Cork', 'Galway', 'Limerick'],
        'Italy' => ['Rome', 'Milan', 'Florence', 'Turin', 'Naples'],
        'Japan' => ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya'],
        'Latvia' => ['Rīga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'],
        'Lithuania' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'],
        'Netherlands' => ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
        'New Zealand' => ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
        'Norway' => ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
        'Poland' => ['Warsaw', 'Kraków', 'Wrocław', 'Gdańsk'],
        'Portugal' => ['Lisbon', 'Porto', 'Braga', 'Coimbra'],
        'Singapore' => ['Singapore'],
        'South Africa' => ['Johannesburg', 'Cape Town', 'Pretoria', 'Durban'],
        'Spain' => ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao'],
        'Sweden' => ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'],
        'Switzerland' => ['Zurich', 'Geneva', 'Basel', 'Bern'],
        'United Arab Emirates' => ['Dubai', 'Abu Dhabi', 'Sharjah'],
        'United Kingdom' => ['London', 'Manchester', 'Birmingham', 'Edinburgh', 'Glasgow'],
        'United States' => ['New York', 'San Francisco', 'Los Angeles', 'Chicago', 'Austin'],
    ],
];
